/* =========================================================
   ADMIN MODULE REGISTRY
   One entry per content type. Drives the sidebar, the generic
   list/add/edit pages at src/app/admin/[module]/*, and the
   generic server actions in src/app/admin/[module]/actions.js.
   Field "type" controls which input AdminForm renders:
     text | textarea | number | boolean | select | image |
     string-list (repeatable plain-text rows) |
     json (freeform JSON textarea, for nested arrays/objects)
========================================================= */

export const adminModules = {
  bookings: {
    label: "Bookings",
    group: "Bookings",
    model: "booking",
    titleField: "packageTitle",
    revalidate: [],
    listColumns: ["packageTitle", "customerName", "customerPhone", "departureDate", "guests", "totalPrice", "status"],
    fields: [
      { name: "packageSlug", label: "Package slug", type: "text", required: true },
      { name: "packageTitle", label: "Package title", type: "text", required: true },
      { name: "departureCity", label: "Departure city", type: "text", required: true },
      { name: "departureDate", label: "Departure date", type: "text", required: true },
      { name: "guests", label: "Guests", type: "number", required: true },
      { name: "totalPrice", label: "Total price (INR)", type: "number", required: true },
      { name: "customerName", label: "Customer name", type: "text", required: true },
      { name: "customerPhone", label: "Customer phone", type: "text", required: true },
      { name: "customerEmail", label: "Customer email", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["New", "Contacted", "Confirmed", "Cancelled"], required: true },
    ],
  },

  packages: {
    label: "Packages",
    group: "Catalog",
    model: "package",
    titleField: "title",
    revalidate: ["/", "/package", "/india", "/world"],
    listColumns: ["title", "slug", "category", "price"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "tourType", label: "Tour Type", type: "text", required: true },
      { name: "days", label: "Days", type: "number", required: true },
      { name: "nights", label: "Nights", type: "number", required: true },
      { name: "cities", label: "Cities count", type: "number", required: true },
      { name: "price", label: "Price (INR)", type: "number", required: true },
      { name: "emi", label: "EMI (INR/month)", type: "number", required: true },
      { name: "rating", label: "Rating", type: "number", step: "0.1" },
      { name: "reviews", label: "Reviews count", type: "number" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "imageUrl", label: "Image", type: "image" },
      { name: "country", label: "Country (World packages)", type: "text" },
      { name: "state", label: "State (India packages)", type: "text" },
      { name: "relatedGroup", label: "Related group key", type: "text" },
      { name: "departureCities", label: "Departure cities", type: "string-list" },
      { name: "highlights", label: "Highlights", type: "string-list", required: true },
      { name: "inclusions", label: "Inclusions", type: "string-list", required: true },
      { name: "exclusions", label: "Exclusions", type: "string-list" },
      { name: "itinerary", label: "Itinerary (JSON array of {day,title,description})", type: "json", required: true },
      { name: "departures", label: "Departures (JSON array of {date,price,status})", type: "json", required: true },
      { name: "needToKnow", label: "Need to know (JSON object)", type: "json" },
      { name: "cancellationPolicy", label: "Cancellation policy (JSON array)", type: "json" },
      { name: "paymentTerms", label: "Payment terms", type: "string-list" },
      { name: "upgrades", label: "Upgrades (JSON array of {title,description})", type: "json" },
      { name: "tourDetails", label: "Tour details (JSON object)", type: "json" },
    ],
  },

  destinations: {
    label: "Destinations (India + World)",
    group: "Catalog",
    model: "destination",
    titleField: "name",
    revalidate: ["/india", "/world"],
    listColumns: ["name", "parent", "slug", "packageCount"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "parent", label: "Parent section", type: "select", options: ["india", "world"], required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "heading", label: "Heading", type: "text", required: true },
      { name: "metaTitle", label: "Meta title", type: "text", required: true },
      { name: "metaDescription", label: "Meta description", type: "textarea", required: true },
      { name: "breadcrumbTrail", label: "Breadcrumb trail", type: "string-list", required: true },
      { name: "packageCount", label: "Package count", type: "number" },
      { name: "liveTourCount", label: "Live tour count", type: "number" },
      { name: "reviewsLabel", label: "Reviews label", type: "text" },
      { name: "intro", label: "Intro", type: "textarea", required: true },
      { name: "introExtra", label: "Intro (extra)", type: "textarea" },
      { name: "tabs", label: "Tabs", type: "string-list" },
      { name: "countries", label: "Countries", type: "string-list" },
      { name: "cities", label: "Cities", type: "string-list" },
      { name: "packageSlugs", label: "Package slugs", type: "string-list", required: true },
      { name: "joiningLeavingCities", label: "Joining/leaving cities", type: "string-list" },
      { name: "related", label: "Related (JSON)", type: "json" },
      { name: "regions", label: "Regions (JSON)", type: "json" },
      { name: "faqHeading", label: "FAQ heading", type: "text" },
      { name: "faqSubheading", label: "FAQ subheading", type: "text" },
      { name: "faqs", label: "FAQs (JSON array of {question,answer})", type: "json" },
      { name: "seoParagraphs", label: "SEO paragraphs", type: "string-list" },
      { name: "seoExtraParagraphs", label: "SEO paragraphs (extra)", type: "string-list" },
    ],
  },

  "departure-cities": {
    label: "Departure Cities",
    group: "Catalog",
    model: "departureCity",
    titleField: "name",
    revalidate: ["/", "/tour-packages-from"],
    listColumns: ["name", "slug", "departures", "startingPrice"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name", label: "City name", type: "text", required: true },
      { name: "departures", label: "Departures", type: "number", required: true },
      { name: "startingPrice", label: "Starting price (INR)", type: "number", required: true },
      { name: "packageCount", label: "Package count", type: "number" },
      { name: "reviewsLabel", label: "Reviews label", type: "text" },
      { name: "intro", label: "Intro", type: "textarea", required: true },
      { name: "introExtra", label: "Intro (extra)", type: "textarea" },
      { name: "packageSlugs", label: "Package slugs", type: "string-list", required: true },
      { name: "linkCloudTargets", label: "Link cloud targets (JSON array of {name,href})", type: "json" },
    ],
  },

  "flight-routes": {
    label: "Flight Routes",
    group: "Flights",
    model: "flightRoute",
    titleField: "slug",
    revalidate: ["/flights"],
    listColumns: ["from", "to", "slug", "minPrice", "maxPrice"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "from", label: "From city", type: "text", required: true },
      { name: "fromCode", label: "From airport code", type: "text", required: true },
      { name: "to", label: "To city", type: "text", required: true },
      { name: "toCode", label: "To airport code", type: "text", required: true },
      { name: "international", label: "International route", type: "boolean" },
      { name: "baseDuration", label: "Base duration (minutes)", type: "number", required: true },
      { name: "minPrice", label: "Min price (INR)", type: "number", required: true },
      { name: "maxPrice", label: "Max price (INR)", type: "number", required: true },
      { name: "count", label: "Flight count", type: "number", required: true },
      { name: "allowStops", label: "Allow connecting flights", type: "boolean" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "relatedTours", label: "Related tours (JSON array of {label,href})", type: "json" },
      { name: "otherRoutes", label: "Other route slugs", type: "string-list" },
    ],
  },

  airports: {
    label: "Airports",
    group: "Flights",
    model: "airport",
    titleField: "city",
    revalidate: ["/flights"],
    listColumns: ["city", "code", "country"],
    fields: [
      { name: "city", label: "City", type: "text", required: true },
      { name: "code", label: "Airport code", type: "text", required: true },
      { name: "country", label: "Country", type: "text", required: true },
    ],
  },

  airlines: {
    label: "Airlines",
    group: "Flights",
    model: "airline",
    titleField: "name",
    revalidate: ["/flights"],
    listColumns: ["name", "code", "color"],
    fields: [
      { name: "name", label: "Airline name (must match flight data exactly)", type: "text", required: true },
      { name: "code", label: "Carrier code (e.g. 6E)", type: "text", required: true },
      { name: "logoUrl", label: "Logo image", type: "image" },
      { name: "color", label: "Fallback badge color (hex, used if no logo)", type: "text", required: true },
    ],
  },

  transport: {
    label: "Transport Options",
    group: "Flights",
    model: "transportOption",
    titleField: "name",
    revalidate: ["/transport"],
    listColumns: ["type", "name", "capacity", "basePrice"],
    fields: [
      { name: "type", label: "Type", type: "select", options: ["Car", "Bus"], required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "image", label: "Image (optional)", type: "image" },
      { name: "capacity", label: "Seating capacity", type: "number", required: true },
      { name: "acType", label: "AC / Non-AC", type: "select", options: ["AC", "Non-AC"], required: true },
      { name: "pricePerKm", label: "Price per km (INR)", type: "number", required: true },
      { name: "basePrice", label: "Base price (INR)", type: "number", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "features", label: "Features", type: "string-list", required: true },
    ],
  },

  "transport-routes": {
    label: "Transport Routes",
    group: "Flights",
    model: "transportRoute",
    titleField: "slug",
    revalidate: ["/transport"],
    listColumns: ["from", "to", "slug", "distanceKm"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "from", label: "From city", type: "text", required: true },
      { name: "to", label: "To city", type: "text", required: true },
      { name: "distanceKm", label: "Distance (km)", type: "number", required: true },
      { name: "duration", label: "Typical duration label", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
    ],
  },

  hotels: {
    label: "Hotels",
    group: "Hotels",
    model: "hotel",
    titleField: "name",
    revalidate: ["/hotels"],
    listColumns: ["name", "city", "starRating", "pricePerNight"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name", label: "Hotel name", type: "text", required: true },
      { name: "city", label: "City", type: "text", required: true },
      { name: "citySlug", label: "City slug (used in URL)", type: "text", required: true },
      { name: "starRating", label: "Star rating (1-5)", type: "number", required: true },
      { name: "rating", label: "Guest rating (e.g. 4.5)", type: "number", step: "0.1" },
      { name: "reviewCount", label: "Review count", type: "number" },
      { name: "address", label: "Address", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "image", label: "Image", type: "image" },
      { name: "pricePerNight", label: "Starting price per night (INR)", type: "number", required: true },
      { name: "amenities", label: "Amenities", type: "string-list", required: true },
      { name: "rooms", label: "Rooms (JSON array of {type, capacity, price, amenities, image?})", type: "json", required: true },
      { name: "checkInTime", label: "Check-in time", type: "text" },
      { name: "checkOutTime", label: "Check-out time", type: "text" },
      { name: "nearbyAttractions", label: "Nearby attractions", type: "string-list" },
    ],
  },

  "india-zones": {
    label: "Zone Cards",
    group: "India Page",
    model: "indiaZoneCard",
    titleField: "name",
    revalidate: ["/india"],
    listColumns: ["region", "name", "tours"],
    fields: [
      { name: "region", label: "Region", type: "select", options: ["North", "South", "West & Central", "East & North East"], required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "tours", label: "Tours label", type: "text", required: true },
      { name: "visual", label: "Gradient classes (fallback if no image)", type: "text", required: true },
      { name: "image", label: "Image", type: "image" },
    ],
  },

  "india-listing": {
    label: "Listing Packages",
    group: "India Page",
    model: "indiaListingPackage",
    titleField: "title",
    revalidate: ["/india"],
    listColumns: ["title", "slug", "price"],
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "image", label: "Image", type: "image", required: true },
      { name: "tags", label: "Tags", type: "string-list" },
      { name: "days", label: "Days label", type: "text", required: true },
      { name: "cities", label: "Cities label", type: "text", required: true },
      { name: "dates", label: "Dates label", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
      { name: "emi", label: "EMI label", type: "text", required: true },
      { name: "highlights", label: "Highlights", type: "text", required: true },
    ],
  },

  "india-explore-tiles": {
    label: "Explore Tiles",
    group: "India Page",
    model: "indiaExploreTile",
    titleField: "name",
    revalidate: ["/india"],
    listColumns: ["group", "name", "tours"],
    fields: [
      { name: "group", label: "Group (city / state / a season name)", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "tours", label: "Tours label", type: "text", required: true },
      { name: "visual", label: "Gradient classes (fallback if no image)", type: "text", required: true },
      { name: "image", label: "Image", type: "image" },
    ],
  },

  "india-explore-interest": {
    label: "Explore by Interest",
    group: "India Page",
    model: "indiaExploreInterest",
    titleField: "title",
    revalidate: ["/india"],
    listColumns: ["title", "tag", "price"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "isDestinationLink", label: "Links to a destination page", type: "boolean" },
      { name: "tag", label: "Tag", type: "text", required: true },
      { name: "days", label: "Days label", type: "text", required: true },
      { name: "cities", label: "Cities label", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
      { name: "emi", label: "EMI label", type: "text", required: true },
    ],
  },

  "india-explore-duration": {
    label: "Explore by Duration",
    group: "India Page",
    model: "indiaExploreDuration",
    titleField: "title",
    revalidate: ["/india"],
    listColumns: ["title", "category", "days", "price"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "days", label: "Days", type: "number", required: true },
      { name: "cities", label: "Cities", type: "number", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
    ],
  },

  "india-blogs": {
    label: "Blog Tiles",
    group: "India Page",
    model: "indiaBlog",
    titleField: "title",
    revalidate: ["/india"],
    listColumns: ["title"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "style", label: "Gradient classes", type: "text", required: true },
    ],
  },

  "india-reviews": {
    label: "Reviews",
    group: "India Page",
    model: "indiaReview",
    titleField: "name",
    revalidate: ["/india"],
    listColumns: ["name", "tour", "category"],
    fields: [
      { name: "name", label: "Guest name", type: "text", required: true },
      { name: "tour", label: "Tour", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "review", label: "Review", type: "textarea", required: true },
      { name: "manager", label: "Tour manager", type: "text", required: true },
    ],
  },

  "india-faqs": {
    label: "FAQs",
    group: "India Page",
    model: "indiaFaq",
    titleField: "question",
    revalidate: ["/india"],
    listColumns: ["question"],
    fields: [
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
    ],
  },

  "home-hero": {
    label: "Hero Cards",
    group: "Home Page",
    model: "heroCard",
    titleField: "title",
    revalidate: ["/"],
    listColumns: ["title", "subtitle"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "subtitle", label: "Subtitle", type: "text", required: true },
    ],
  },

  "home-destinations": {
    label: "Destination Strip",
    group: "Home Page",
    model: "homeDestination",
    titleField: "name",
    revalidate: ["/"],
    listColumns: ["name", "tourCount", "icon"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "tourCount", label: "Tour count label", type: "text", required: true },
      { name: "icon", label: "Icon (lucide-react name)", type: "text", required: true },
    ],
  },

  "home-live-tours": {
    label: "Live Tours",
    group: "Home Page",
    model: "liveTourCard",
    titleField: "destination",
    revalidate: ["/"],
    listColumns: ["destination", "liveTourCount"],
    fields: [
      { name: "destination", label: "Destination", type: "text", required: true },
      { name: "liveTourCount", label: "Live tour count", type: "text", required: true },
      { name: "color1", label: "Gradient color 1", type: "text", required: true },
      { name: "color2", label: "Gradient color 2", type: "text", required: true },
      { name: "color3", label: "Gradient color 3", type: "text", required: true },
      { name: "image", label: "Image", type: "image" },
    ],
  },

  "home-china-promo": {
    label: "China Promo Packages",
    group: "Home Page",
    model: "chinaPromoPackage",
    titleField: "name",
    revalidate: ["/"],
    listColumns: ["name", "days", "price"],
    fields: [
      { name: "days", label: "Days label", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
      { name: "slug", label: "Package slug", type: "text", required: true },
    ],
  },

  "home-most-loved-promo": {
    label: "Most Loved — Promo Strip",
    group: "Home Page",
    model: "mostLovedPromoDestination",
    titleField: "name",
    revalidate: ["/"],
    listColumns: ["name", "days", "price"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "days", label: "Days label", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
    ],
  },

  "home-most-loved": {
    label: "Most Loved Destinations",
    group: "Home Page",
    model: "mostLovedDestination",
    titleField: "name",
    revalidate: ["/"],
    listColumns: ["name", "price", "guests"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
      { name: "guests", label: "Guests label", type: "text", required: true },
      { name: "slug", label: "Package slug", type: "text", required: true },
      { name: "image", label: "Image", type: "image" },
    ],
  },

  "home-trust-stats": {
    label: "Trust Stats",
    group: "Home Page",
    model: "trustStat",
    titleField: "label",
    revalidate: ["/"],
    listColumns: ["value", "label", "icon"],
    fields: [
      { name: "value", label: "Value", type: "text", required: true },
      { name: "label", label: "Label", type: "text", required: true },
      { name: "icon", label: "Icon (lucide-react name)", type: "text", required: true },
    ],
  },

  "home-trust-reviews": {
    label: "Trust Reviews",
    group: "Home Page",
    model: "trustReview",
    titleField: "destination",
    revalidate: ["/"],
    listColumns: ["destination", "type", "guest"],
    fields: [
      { name: "type", label: "Type", type: "text", required: true },
      { name: "destination", label: "Destination", type: "text", required: true },
      { name: "excerpt", label: "Excerpt", type: "textarea", required: true },
      { name: "guest", label: "Guest name", type: "text", required: true },
      { name: "date", label: "Date label", type: "text", required: true },
    ],
  },

  "home-featured-tour": {
    label: "Featured Tour Slides",
    group: "Home Page",
    model: "featuredTourSlide",
    titleField: "title",
    revalidate: ["/"],
    listColumns: ["title", "region", "price"],
    fields: [
      { name: "region", label: "Region", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "locations", label: "Locations", type: "text", required: true },
      { name: "days", label: "Days label", type: "text", required: true },
      { name: "date", label: "Date label", type: "text", required: true },
      { name: "departure", label: "Departure label", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
      { name: "image", label: "Image", type: "image" },
    ],
  },

  "home-continue-travel": {
    label: "Continue Travel",
    group: "Home Page",
    model: "continueTravelTour",
    titleField: "name",
    revalidate: ["/"],
    listColumns: ["name", "duration", "price"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "duration", label: "Duration label", type: "text", required: true },
      { name: "price", label: "Price label", type: "text", required: true },
      { name: "cta", label: "CTA label", type: "text", required: true },
      { name: "slug", label: "Package slug", type: "text", required: true },
    ],
  },

  "home-inclusions": {
    label: "Tour Inclusions",
    group: "Home Page",
    model: "tourInclusionFeature",
    titleField: "title",
    revalidate: ["/"],
    listColumns: ["title", "icon"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "icon", label: "Icon (lucide-react name)", type: "text", required: true },
    ],
  },

  "home-faq": {
    label: "FAQ",
    group: "Home Page",
    model: "faqItem",
    titleField: "question",
    revalidate: ["/"],
    listColumns: ["question", "category"],
    fields: [
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "category", label: "Category", type: "text" },
    ],
  },

  "home-promo-slides": {
    label: "Promo Carousel Slides",
    group: "Home Page",
    model: "promoSlide",
    titleField: "title",
    revalidate: ["/"],
    listColumns: ["type", "title"],
    fields: [
      { name: "type", label: "Type", type: "select", options: ["welcome", "poster"], required: true },
      { name: "title", label: "Title", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "ctaLabel", label: "CTA label", type: "text" },
      { name: "price", label: "Price label", type: "text" },
      { name: "gradientFrom", label: "Gradient — from color (hex)", type: "text" },
      { name: "gradientVia", label: "Gradient — via color (hex)", type: "text" },
      { name: "gradientTo", label: "Gradient — to color (hex)", type: "text" },
    ],
  },
};

export const adminModuleGroups = ["Bookings", "Catalog", "Home Page", "India Page", "Flights", "Hotels"];

export function getModule(slug) {
  return adminModules[slug] ?? null;
}
